spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:finance-management-db
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
